baseURL = "https://sasanasadiabadi.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Personel Webpage of Sasan Asadiabadi"
theme = "anatole"

summarylength = 100
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"


[params]
title = "I'm Sasan"
author = "Sasan Asadiabadi"
description = "Personal homepage of Sasan Asadiabadi"
profilePicture = "images/me.jpg"
contentratio = 0.85
readMore = true
googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"



[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/sasan-asadiabadi-1211678a/"

[[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sasanasadiabadi"

[[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:sabadi15@ku.edu.tr"


[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Publications"
  weight = 200
  identifier = "publications"
  url = "/publications/"
  
  [[menu.main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/cv/"



[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "mathjax"  # options: "katex", "mathjax". default is "katex".
